# src/main/resources/api-spec.yaml
openapi: 3.0.3
info:
  title: Fine dine Management API
  version: 1.0.0
  description: API for fine dine management
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /restaurants:
    get:
      summary: Get all restaurants
      operationId: getAllRestaurants
      responses:
        '200':
          description: A list of restaurants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
    post:
      summary: Create a new restaurant
      operationId: createRestaurant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
      responses:
        '201':
          description: Restaurant created successfully
          content:
            application/json:
              schema:
                $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
        '400':
          description: Invalid input
  /restaurants/{restaurantId}:
    get:
      summary: Get a restaurant by its unique id
      operationId: getRestaurantById
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
          description: Restaurant ID
      responses:
        '200':
          description: A restaurant object
          content:
            application/json:
              schema:
                $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
        '404':
          description: Restaurant not found
    put:
      summary: Update a restaurant by its unique id
      operationId: updateRestaurant
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
          description: Restaurant ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
      responses:
        '200':
          description: Restaurant updated successfully
          content:
            application/json:
              schema:
                $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
        '404':
          description: Restaurant not found
        '400':
          description: Invalid input
    patch:
      summary: Partially update a restaurant by its unique id
      operationId: patchRestaurant
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
          description: Restaurant ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
      responses:
        '200':
          description: Restaurant partially updated successfully
          content:
            application/json:
              schema:
                $ref: 'restaurant-models.yaml#/components/schemas/Restaurant'
        '404':
          description: Restaurant not found
        '400':
          description: Invalid input
    delete:
      summary: Delete a restaurant by its unique id
      operationId: deleteRestaurant
      parameters:
        - name: restaurantId
          in: path
          required: true
          schema:
            type: string
          description: Restaurant ID
      responses:
        '204':
          description: Restaurant deleted successfully
        '404':
          description: Restaurant not found
  /users:
    get:
      summary: Get all users
      operationId: getAllUsers
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'user-models.yaml#/components/schemas/User'
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'user-models.yaml#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: 'user-models.yaml#/components/schemas/User'
        '400':
          description: Invalid input
  /users/{userId}:
    get:
      summary: Get a user by their unique ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                $ref: 'user-models.yaml#/components/schemas/User'
        '404':
          description: User not found

    put:
      summary: Update a user by their unique ID
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'user-models.yaml#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: 'user-models.yaml#/components/schemas/User'
        '404':
          description: User not found
        '400':
          description: Invalid input

    delete:
      summary: Delete a user by their unique ID
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found

    patch:
      summary: Partially update a user by their unique ID
      operationId: patchUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: User ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'user-models.yaml#/components/schemas/User'
      responses:
        '200':
          description: User partially updated successfully
          content:
            application/json:
              schema:
                $ref: 'user-models.yaml#/components/schemas/User'
        '404':
          description: User not found
        '400':
          description: Invalid input
  /items:
    get:
      summary: Retrieve all items
      operationId: getItems
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'item-models.yaml#/components/schemas/Item'
    post:
      summary: Create multiple items
      operationId: createItems
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: 'item-models.yaml#/components/schemas/Item'
      responses:
        '201':
          description: Items created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'item-models.yaml#/components/schemas/Item'
  /items/{itemId}:
    get:
      summary: Retrieve an item by ID
      operationId: getItemById
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the item to retrieve
      responses:
        '200':
          description: The requested item
          content:
            application/json:
              schema:
                $ref: 'item-models.yaml#/components/schemas/Item'
        '404':
          description: Item not found

    put:
      summary: Update an item by ID
      operationId: updateItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the item to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'item-models.yaml#/components/schemas/Item'
      responses:
        '200':
          description: Item updated successfully
          content:
            application/json:
              schema:
                $ref: 'item-models.yaml#/components/schemas/Item'
        '404':
          description: Item not found

    patch:
      summary: Partially update an item by ID
      operationId: patchItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the item to patch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Fields to update
              properties:
                productName:
                  type: string
                productDescription:
                  type: string
                itemStatus:
                  type: string
              example:
                productName: "Updated Name"
                itemStatus: "unavailable"
      responses:
        '200':
          description: Item patched successfully
          content:
            application/json:
              schema:
                $ref: 'item-models.yaml#/components/schemas/Item'
        '404':
          description: Item not found

    delete:
      summary: Delete an item by ID
      operationId: deleteItem
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the item to delete
      responses:
        '204':
          description: Item deleted successfully
        '404':
          description: Item not found
